[pytest]
testpaths = tests # ищем только в папке тест 
python_files = test_*.py # файлы начинаются с тест 
python_classes = Test* # класс начинается с тест 
python_functions = test_* # функции начинаются с тест 
addopts = -v --tb=short # отчет 